### ISSUE TITLE
Error when running with a space in the user name

### ISSUE THREAD

**Issue by TrymBeast** [matkoch/nswag#30]
When I try to run the NSwagAspNetCoreToSwagger task with the .NetCore 2.2 NSwag runtime I get an error because my user name has a space in it.

I guess that the following line should surround the dotnet-nswag.dll path with double quotes.

https://github.com/matkoch/nswag/blob/04d31a2f6b7a237fa985d4d24f566a6bd2316d30/src/Nuke.NSwag/NSwagSettings.cs#L32

**Comment by matkoch** [comment]
Fixed with Nuke.Common 0.24.0

**Comment by matkoch** [comment]
@TrymBeast please star the main project https://github.com/nuke-build/nuke

**Comment by TrymBeast** [comment]
@matkoch done ;)

Btw, I have tried upgrading the Nuke.Common with the prerelease, but unfortunately, there are breaking changes and I get this error:
```
Could not load type 'AbsolutePath' from assembly 'Nuke.Common, Version=0.24.0.0, Culture=neutral, PublicKeyToken=null'.
   at Nuke.NSwag.NSwagSettings.GetNetCoreDllPath(String runtime)
   at Nuke.NSwag.NSwagSettings.ConfigureArguments(Arguments arguments)
   at Nuke.NSwag.NSwagAspNetCoreToSwaggerSettings.ConfigureArguments(Arguments arguments)
   at Nuke.Common.Tooling.ToolSettings.GetArguments()
   at Nuke.Common.Tooling.ProcessTasks.StartProcess(ToolSettings toolSettings)
   at Nuke.NSwag.NSwagTasks.NSwagAspNetCoreToSwagger(NSwagAspNetCoreToSwaggerSettings toolSettings)
   at Nuke.NSwag.NSwagTasks.NSwagAspNetCoreToSwagger(Configure`1 configurator)
   at Build.<>c.<get_ApiClient>b__10_1() in C:\Work\Libraries\MyApp\src\Build.cs:line 97
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_0(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
   at Nuke.Common.Execution.BuildExecutor.<>c__DisplayClass2_0.<Execute>b__0(ExecutableTarget x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, IReadOnlyCollection`1 skippedTargets)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
```

**Comment by matkoch** [comment]
NSwag is contained in Nuke.Common. No need for an additional package.

**Comment by TrymBeast** [comment]
@matkoch Right, thanks! Maybe add some note in this repository that this is included in the Nuke.Common from version x?

After trying with Nuke.Common I noticed that the Nuke.NSwag had more values in the Runtime enum, Netcore22 and Netcore30. And even this repo seems to be out of sync with the latest Nuke.NSwag package.
